### ISSUE TITLE
Refactor Polish

### ISSUE THREAD

**Issue by bdemann** [demergent-labs/cdk_framework#42]
Now that the broad strokes for the refactor are done we can add some final polish

- [x] #50
- [x] Create readme (see comments below)
    - [x] for users
    - [x] for developers
    - [x] see also https://github.com/demergent-labs/cdk_framework/issues/42#issuecomment-1462913494
- [x] Get rid of the is_type and as_type: see https://github.com/demergent-labs/cdk_framework/issues/27#issuecomment-1424236189
- [x] Make sure our generate lib file has no errors https://github.com/demergent-labs/cdk_framework/issues/32
- [x] #45
- [x] Make sure all python keywords are handled correctly https://github.com/demergent-labs/kybra/issues/238

**Comment by bdemann** [comment]
For the README
There are two kinds of things we want to pass in as the parental prefix, either the name of the parent, or the name that we want the thing to take on if it's inline. That's it. So if it asks for a parent's name give that, if it asks for a name, give that.

**Comment by bdemann** [comment]
Moved these tickets to the zenhub epic, so I'm closing this collector ticket.

**Comment by bdemann** [comment]
This ticket didn't get closed so I am closing it now.
